export const NOTIFICATION_TYPES = {
  donation: 'donation',
  milestone: 'milestone',
  agency_response: 'agency_response',
  chat_message: 'chat_message',
  like: 'like',
  comment: 'comment',
  share: 'share',
  review_received: 'review_received',
  verification_status: 'verification_status',
  account_status: 'account_status',
  campaign_flagged: 'campaign_flagged',
  admin_broadcast: 'admin_broadcast',
  new_request: 'new_request',
  booking_update: 'booking_update',
  payment_received: 'payment_received',
  withdrawal_status: 'withdrawal_status',
  friend_request: 'friend_request',
  shared_file: 'shared_file',
  new_call: 'new_call',
  system_alert: 'system_alert',
} as const;

export type NotificationType = typeof NOTIFICATION_TYPES[keyof typeof NOTIFICATION_TYPES];

export const NOTIFICATION_TYPE_LABELS: Record<NotificationType, string> = {
  donation: 'Donation',
  milestone: 'Campaign Milestone',
  agency_response: 'Agency Response',
  chat_message: 'Messages',
  like: 'Likes',
  comment: 'Comments',
  share: 'Shares',
  review_received: 'Reviews',
  verification_status: 'Verification',
  account_status: 'Account',
  campaign_flagged: 'Campaign Flags',
  admin_broadcast: 'Admin Announcements',
  new_request: 'Trip Requests',
  booking_update: 'Bookings',
  payment_received: 'Payments',
  withdrawal_status: 'Withdrawals',
  friend_request: 'Friend Requests',
  shared_file: 'Shared Files',
  new_call: 'Calls',
  system_alert: 'System',
};
